### ISSUE TITLE
Randomly doesn't compile css files

### ISSUE THREAD

**Issue by Kakise** [Kakise/Blog#24]
PhantomJS throws an error related to null stdin in some cases:

```
11:41:12 PM: ERROR Asset render failed: css/style.css
11:41:12 PM: TypeError: Cannot read property 'stdin' of null
11:41:12 PM:     at write (/opt/build/repo/node_modules/phridge/lib/Phantom.js:259:18)
11:41:12 PM:     at /opt/build/repo/node_modules/phridge/lib/Phantom.js:181:9
11:41:12 PM:     at init (/opt/build/repo/node_modules/when/lib/makePromise.js:39:5)
11:41:12 PM:     at new Promise (/opt/build/repo/node_modules/when/lib/makePromise.js:27:53)
11:41:12 PM:     at Function.promise (/opt/build/repo/node_modules/when/when.js:97:10)
11:41:12 PM:     at Phantom._send (/opt/build/repo/node_modules/phridge/lib/Phantom.js:170:17)
11:41:12 PM:     at Page.run (/opt/build/repo/node_modules/phridge/lib/Page.js:62:25)
11:41:12 PM:     at Object.findAll (/opt/build/repo/node_modules/uncss/src/phantom.js:194:17)
11:41:12 PM:     at /opt/build/repo/node_modules/uncss/src/lib.js:156:24
11:41:12 PM:     at tryCatcher (/opt/build/repo/node_modules/uncss/node_modules/bluebird/js/main/util.js:26:23)
11:41:12 PM:     at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/uncss/node_modules/bluebird/js/main/promise.js:503:31)
11:41:12 PM:     at Promise._settlePromiseAt (/opt/build/repo/node_modules/uncss/node_modules/bluebird/js/main/promise.js:577:18)
11:41:12 PM:     at Promise._settlePromises (/opt/build/repo/node_modules/uncss/node_modules/bluebird/js/main/promise.js:693:14)
11:41:12 PM:     at Async._drainQueue (/opt/build/repo/node_modules/uncss/node_modules/bluebird/js/main/async.js:123:16)
11:41:12 PM:     at Async._drainQueues (/opt/build/repo/node_modules/uncss/node_modules/bluebird/js/main/async.js:133:10)
11:41:12 PM:     at Immediate.Async.drainQueues [as _onImmediate] (/opt/build/repo/node_modules/uncss/node_modules/bluebird/js/main/async.js:15:14)
11:41:12 PM:     at runCallback (timers.js:794:20)
11:41:12 PM:     at tryOnImmediate (timers.js:752:5)
11:41:12 PM:     at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**Comment by Kakise** [comment]
Finally fixed

**Comment by Kakise** [comment]
Nope. Still buggy as hell.

https://github.com/Kakise/Blog/pull/28

**Comment by Kakise** [comment]
Removing uncss fixes the bug.
